block: true
debug: false
hooks:
- className: java/lang/ProcessBuilder
  methodDesc: ()Ljava/lang/Process;
  methodName: start
  vulTYpe: 1
- className: javax/naming/InitialContext
  methodDesc: (Ljava/lang/String;)Ljava/lang/Object;
  methodName: lookup
  vulTYpe: 2
version: '0.1'